version: '3.9'

volumes:
  yaml_postgres_data:
  yaml_staticfiles:
  yaml_mediafiles:

services:
  yaml_db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - yaml_postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGGSSENCMODE=disable

  yaml_web:
    build: .
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:4001
    volumes:
      - yaml_staticfiles:/code/static/
      - yaml_mediafiles:/code/media/
    ports:
      - 4001:4001
    depends_on:
      - yaml_db
    env_file:
      - ./.env

  yaml_nginx:
    build: ./nginx
    volumes:
      - yaml_staticfiles:/code/static/
      - yaml_mediafiles:/code/media/
    ports:
      - "8081:80"
    depends_on:
      - yaml_web
